if $SHELL_DEBUG; then
    echo "Running .local/zshrc"
fi

# NOTE: We will keep this conda config in a system-specific file because it can
# vary from system to system. It is also shell-specific.
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/ntraft/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/ntraft/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/ntraft/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/ntraft/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

